-- TABLE & SEQUENCE DROP
DROP TABLE CUSTOMER;
DROP TABLE FILEBOARD;
DROP TABLE BOOK;

DROP SEQUENCE FILEBOARD_SEQ;
DROP SEQUENCE BOOK_SEQ;

-- TABLE & SEQUENCE CREATE
CREATE TABLE CUSTOMER (
    CID VARCHAR2(50) PRIMARY KEY,
    CPW VARCHAR2(50) NOT NULL,
    CNAME VARCHAR2(50) NOT NULL,
    CTEL VARCHAR2(50),
    CEMAIL VARCHAR2(50),
    CADDRESS VARCHAR2(250),
    CGENDER VARCHAR2(10),
    CBIRTH DATE,
    CRDATE DATE DEFAULT SYSDATE
);

CREATE TABLE FILEBOARD (
    FNUM NUMBER(7,0) PRIMARY KEY,
    CID VARCHAR2(50) REFERENCES CUSTOMER(CID),
    FSUBJECT VARCHAR2(50) NOT NULL,
    FCONTENT VARCHAR2(4000),
    FFILENAME VARCHAR2(50),
    FPW VARCHAR2(50) NOT NULL,
    FHIT NUMBER(7,0) NOT NULL,
    FREF NUMBER(7,0) NOT NULL,
    FRE_STEP NUMBER(7) NOT NULL,
    FRE_LEVEL NUMBER(1) NOT NULL,
    FIP VARCHAR2(50) NOT NULL,
    FRDATE DATE DEFAULT SYSDATE
);

CREATE TABLE BOOK (
    BID NUMBER(7,0) PRIMARY KEY,
    BTITLE VARCHAR2(50) NOT NULL,
    BPRICE NUMBER(7) NOT NULL,
    BIMAGE1 VARCHAR2(50) NOT NULL,
    BIMAGE2 VARCHAR2(50) NOT NULL,
    BCONTENT VARCHAR2(4000),
    BDISCOUNT NUMBER(3) NOT NULL,
    BRDATE DATE DEFAULT SYSDATE
);

CREATE SEQUENCE FILEBOARD_SEQ MAXVALUE 9999999 NOCACHE NOCYCLE;
CREATE SEQUENCE BOOK_SEQ MAXVALUE 9999999 NOCACHE NOCYCLE;