-- table & sequence drop
DROP TABLE MVC_BOARD;
DROP SEQUENCE MVC_BOARD_SEQ;

-- table & sequence create
CREATE TABLE MVC_BOARD(
    BID NUMBER(6) PRIMARY KEY,
    BNAME VARCHAR2(50) NOT NULL,
    BTITLE VARCHAR2(100) NOT NULL,
    BCONTENT VARCHAR2(1000),
    BDATE DATE DEFAULT SYSDATE NOT NULL, -- �ۼ���
    BHIT NUMBER(6) DEFAULT 0 NOT NULL, -- ��ȸ��
    BGROUP NUMBER(6) NOT NULL, -- �����̸� BID�� ����, �亯���� ��� ������ BGROUP�� ����
    BSTEP NUMBER(3) NOT NULL, -- ���� �׷쳻 ��� ����
    BINDENT NUMBER(3) NOT NULL, -- �鿩���� ����
    BIP VARCHAR2(20)
);
CREATE SEQUENCE MVC_BOARD_SEQ MAXVALUE 999999 NOCACHE NOCYCLE;

-- dummy data
INSERT INTO MVC_BOARD (BID, BNAME, BTITLE, BCONTENT, BGROUP, BSTEP, BINDENT, BIP)
    VALUES (MVC_BOARD_SEQ.NEXTVAL, 'ȫ', '����', NULL, MVC_BOARD_SEQ.CURRVAL, 0, 0, '192.1.1.2');
INSERT INTO MVC_BOARD (BID, BNAME, BTITLE, BCONTENT, BGROUP, BSTEP, BINDENT, BIP)
    VALUES (MVC_BOARD_SEQ.NEXTVAL, '��', '���', NULL, MVC_BOARD_SEQ.CURRVAL, 0, 0, '192.1.1.5');
    -- 2������ ���
INSERT INTO MVC_BOARD (BID, BNAME, BTITLE, BCONTENT, BGROUP, BSTEP, BINDENT, BIP)
    VALUES (MVC_BOARD_SEQ.NEXTVAL, '��', '��', '��', 2, 1, 1, '127.1.1.1');
SELECT * FROM MVC_BOARD;

-- dao�� �� query
-- 1. �۸��(startRow ~ endRow����)
SELECT * FROM MVC_BOARD ORDER BY BGROUP DESC, BSTEP;
SELECT ROWNUM RN, A.* FROM (SELECT * FROM MVC_BOARD ORDER BY BGROUP DESC, BSTEP) A;
SELECT * 
    FROM (SELECT ROWNUM RN, A.* 
        FROM (SELECT * FROM MVC_BOARD ORDER BY BGROUP DESC, BSTEP) A)
    WHERE RN BETWEEN 2 AND 3;
    
-- 2. ��ü �� ����
SELECT COUNT(*) FROM MVC_BOARD;

-- 3. ���� ����
INSERT INTO MVC_BOARD (BID, BNAME, BTITLE, BCONTENT, BGROUP, BSTEP, BINDENT, BIP)
    VALUES (MVC_BOARD_SEQ.NEXTVAL, 'ȫ', 'TITLE', NULL, MVC_BOARD_SEQ.CURRVAL, 0, 0, '192.1.1.2');

-- 4. BID�� ��ȸ�� 1 �ø���
UPDATE MVC_BOARD SET BHIT = BHIT + 1
    WHERE BID = 1;

-- 5. BID�� DTO ��������(�� ���� �󼼺���, �� ����view, �亯��view)
SELECT * FROM MVC_BOARD WHERE BID = 1;

-- 6. �� ����
UPDATE MVC_BOARD SET BNAME = 'ȫ����',
                     BTITLE = '����ٲ�',
                     BCONTENT = '�����ٲ�',
                     BIP = '163.1.1.1'
    WHERE BID = 1;

-- 7. �� ����
DELETE FROM MVC_BOARD WHERE BID = 1;
SELECT * FROM MVC_BOARD;

-- 8. �亯�� ������ ����(STEP a) - 2������ �亯
UPDATE MVC_BOARD SET BSTEP = BSTEP + 1
    WHERE BGROUP = 2 AND BSTEP > 0;

-- 9. �亯�� ���� - 2������ �亯
INSERT INTO MVC_BOARD (BID, BNAME, BTITLE, BCONTENT, BGROUP, BSTEP, BINDENT, BIP)
    VALUES (MVC_BOARD_SEQ.NEXTVAL, '��', 'T', NULL, 2, 1, 1, '192.1.2.1');

COMMIT;
SELECT * FROM MVC_BOARD ORDER BY BGROUP DESC, BSTEP;
select * from MVC_BOARD;