-- table & sequence drop
DROP TABLE MVC_BOARD;
DROP SEQUENCE MVC_BOARD_SEQ;

-- table & sequence create
CREATE TABLE MVC_BOARD(
    BID NUMBER(6) PRIMARY KEY,
    BNAME VARCHAR2(50) NOT NULL,
    BTITLE VARCHAR2(100) NOT NULL,
    BCONTENT VARCHAR2(1000),
    BDATE DATE DEFAULT SYSDATE NOT NULL, -- 작성일
    BHIT NUMBER(6) DEFAULT 0 NOT NULL, -- 조회수
    BGROUP NUMBER(6) NOT NULL, -- 원글이면 BID와 같고, 답변글일 경우 원글의 BGROUP와 같음
    BSTEP NUMBER(3) NOT NULL, -- 같은 그룹내 출력 순서
    BINDENT NUMBER(3) NOT NULL, -- 들여쓰기 정도
    BIP VARCHAR2(20)
);
CREATE SEQUENCE MVC_BOARD_SEQ MAXVALUE 999999 NOCACHE NOCYCLE;

-- dummy data
INSERT INTO MVC_BOARD (BID, BNAME, BTITLE, BCONTENT, BGROUP, BSTEP, BINDENT, BIP)
    VALUES (MVC_BOARD_SEQ.NEXTVAL, '홍', '제목', NULL, MVC_BOARD_SEQ.CURRVAL, 0, 0, '192.1.1.2');
INSERT INTO MVC_BOARD (BID, BNAME, BTITLE, BCONTENT, BGROUP, BSTEP, BINDENT, BIP)
    VALUES (MVC_BOARD_SEQ.NEXTVAL, '김', '비와', NULL, MVC_BOARD_SEQ.CURRVAL, 0, 0, '192.1.1.5');
    -- 2번글의 답글
INSERT INTO MVC_BOARD (BID, BNAME, BTITLE, BCONTENT, BGROUP, BSTEP, BINDENT, BIP)
    VALUES (MVC_BOARD_SEQ.NEXTVAL, '이', '답', '답', 2, 1, 1, '127.1.1.1');
SELECT * FROM MVC_BOARD;

-- dao에 들어갈 query
-- 1. 글목록(startRow ~ endRow까지)
SELECT * FROM MVC_BOARD ORDER BY BGROUP DESC, BSTEP;
SELECT ROWNUM RN, A.* FROM (SELECT * FROM MVC_BOARD ORDER BY BGROUP DESC, BSTEP) A;
SELECT * 
    FROM (SELECT ROWNUM RN, A.* 
        FROM (SELECT * FROM MVC_BOARD ORDER BY BGROUP DESC, BSTEP) A)
    WHERE RN BETWEEN 2 AND 3;
    
-- 2. 전체 글 갯수
SELECT COUNT(*) FROM MVC_BOARD;

-- 3. 원글 쓰기
INSERT INTO MVC_BOARD (BID, BNAME, BTITLE, BCONTENT, BGROUP, BSTEP, BINDENT, BIP)
    VALUES (MVC_BOARD_SEQ.NEXTVAL, '홍', 'TITLE', NULL, MVC_BOARD_SEQ.CURRVAL, 0, 0, '192.1.1.2');

-- 4. BID로 조회수 1 올리기
UPDATE MVC_BOARD SET BHIT = BHIT + 1
    WHERE BID = 1;

-- 5. BID로 DTO 가져오기(글 내용 상세보기, 글 수정view, 답변글view)
SELECT * FROM MVC_BOARD WHERE BID = 1;

-- 6. 글 수정
UPDATE MVC_BOARD SET BNAME = '홍수정',
                     BTITLE = '제목바꿈',
                     BCONTENT = '본문바꿈',
                     BIP = '163.1.1.1'
    WHERE BID = 1;

-- 7. 글 삭제
DELETE FROM MVC_BOARD WHERE BID = 1;
SELECT * FROM MVC_BOARD;

-- 8. 답변글 저장전 선행(STEP a) - 2번글의 답변
UPDATE MVC_BOARD SET BSTEP = BSTEP + 1
    WHERE BGROUP = 2 AND BSTEP > 0;

-- 9. 답변글 쓰기 - 2번글의 답변
INSERT INTO MVC_BOARD (BID, BNAME, BTITLE, BCONTENT, BGROUP, BSTEP, BINDENT, BIP)
    VALUES (MVC_BOARD_SEQ.NEXTVAL, '진', 'T', NULL, 2, 1, 1, '192.1.2.1');

COMMIT;
SELECT * FROM MVC_BOARD ORDER BY BGROUP DESC, BSTEP;