-- 테이블 및 시퀀스 삭제
DROP TABLE PERSON;
DROP TABLE JOB;
DROP SEQUENCE PERSON_NO_SQ;

-- 테이블 및 시퀀스 생성
CREATE TABLE JOB(
    JNO NUMBER(2,0) PRIMARY KEY,
    JNAME VARCHAR2(50)
);
CREATE TABLE PERSON (
    PNO NUMBER(5) PRIMARY KEY,
    PNAME VARCHAR2(50) NOT NULL,
    JNO NUMBER(2,0) REFERENCES JOB(JNO) NOT NULL,
    KOR NUMBER(3) CHECK (KOR>=0),
    ENG NUMBER(3) CHECK (ENG>=0),
    MAT NUMBER(3) CHECK (MAT>=0)
);
CREATE SEQUENCE PERSON_NO_SQ 
    MAXVALUE 9999
    NOCACHE
    NOCYCLE;

-- 더미데이터 insert (정우성 ~ 송혜교)
INSERT INTO JOB VALUES (10, '배우');
INSERT INTO JOB VALUES (20, '가수');
INSERT INTO PERSON VALUES (PERSON_NO_SQ.NEXTVAL, '정우성', 10, 90, 80, 81);
INSERT INTO PERSON VALUES (PERSON_NO_SQ.NEXTVAL, '박세영', 10, 80, 90, 80);
INSERT INTO PERSON VALUES (PERSON_NO_SQ.NEXTVAL, '배수지', 20, 20, 90, 90);
INSERT INTO PERSON VALUES (PERSON_NO_SQ.NEXTVAL, '설수현', 20, 95, 95, 95);
INSERT INTO PERSON VALUES (PERSON_NO_SQ.NEXTVAL, '송혜교', 10, 100, 100, 100);

SELECT * FROM JOB;
SELECT * FROM PERSON;

-- 기능별 query 작성(1, 2, 3)
-- 1.
INSERT INTO PERSON VALUES (PERSON_NO_SQ.NEXTVAL, '홍길동', (SELECT JNO FROM JOB WHERE JNAME = '가수'), 90, 80, 81);
ROLLBACK;

-- 2.
SELECT ROWNUM||'등' RN, S.* 
    FROM(SELECT P.PNAME, JNAME, KOR, ENG, MAT,SUM 
            FROM PERSON P,JOB J,(SELECT PNAME, KOR+ENG+MAT SUM 
                                    FROM PERSON ORDER BY SUM DESC)A 
                                    WHERE P.PNAME = A.PNAME AND P.JNO = J.JNO AND JNAME = UPPER('가수')
                                    ORDER BY SUM DESC)S;

--  3.
SELECT RN||'등' RN, P.PNAME, JNAME, P.KOR, P.ENG, P.MAT, SUM 
    FROM JOB J, PERSON P,(SELECT ROWNUM RN, PNAME, SUM 
        FROM(SELECT PNAME, KOR+ENG+MAT SUM FROM PERSON ORDER BY SUM DESC))A 
    WHERE J.JNO=P.JNO AND A.PNAME = P.PNAME;
    
SELECT JNAME FROM JOB;

commit;