-- [VIII] Sequence : 순차번호 생성기. 대부분 인위적인 PK 사용 용도
DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ
    START WITH 1 -- 1부터 시작 (생략시 1)
    INCREMENT BY 1 -- 1씩 증가 (생략시 1씩 증가)
    MAXVALUE 9999 -- 최대값
    MINVALUE 1 -- 최소값
    NOCACHE
    NOCYCLE;
    
SELECT FRIEND_SEQ.NEXTVAL FROM DUAL; -- SEQ의 다음 순차번호
SELECT FRIEND_SEQ.CURRVAL FROM DUAL; -- SEQ의 현재 값

DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ
    MAXVALUE 9999
    NOCACHE
    NOCYCLE;
    
DROP TABLE FRIEND;
CREATE TABLE FRIEND(
    NUM NUMBER(4) PRIMARY KEY, -- SEQ 이용
    NAME VARCHAR2(30) NOT NULL,
    TEL VARCHAR2(20) UNIQUE, -- NULL 허용
    ADDRESS VARCHAR2(255),
    LAST_MODIFIED DATE DEFAULT SYSDATE -- 최종수정일
);
SELECT * FROM FRIEND;
INSERT INTO FRIEND (NUM, NAME, TEL, ADDRESS)
    VALUES (FRIEND_SEQ.NEXTVAL, '홍길동', NULL, '서울시 서대문구');
SELECT * FROM FRIEND;
--INSERT INTO FRIEND (NUM, NAME, TEL, ADDRESS)
    --VALUES (FRIEND_SEQ.NEXTVAL, NULL, '010-9999-9999', '서울시 마포구'); -- 에러(NOT NULL)
INSERT INTO FRIEND (NUM, NAME, TEL, ADDRESS)
    VALUES (FRIEND_SEQ.NEXTVAL, '김길동', '010-9999-9999', '서울시 마포구');
--INSERT INTO FRIEND (NUM, NAME, TEL, ADDRESS)
   -- VALUES (FRIEND_SEQ.NEXTVAL, '신길동', '010-9999-9999', '서울시 영등포구'); -- 에러(UNIQUE)
INSERT INTO FRIEND (NUM, NAME, TEL, ADDRESS)
    VALUES (FRIEND_SEQ.NEXTVAL, '진길동', '010-8888-8888', '수원시 영통구');
SELECT * FROM FRIEND;
    -- ex. 초기값 101부터 최대값 999,999까지 1씩 증가하는 TEST_SEQ 시퀀스를 생성하고 시퀀스 수를 사용
CREATE SEQUENCE TEST_SEQ 
    START WITH 101
    MAXVALUE 999999
    NOCACHE
    NOCYCLE;
SELECT TEST_SEQ.NEXTVAL FROM DUAL;
SELECT TEST_SEQ.CURRVAL FROM DUAL;
