DROP TABLE CART;
DROP TABLE ORDERDETAIL;
DROP TABLE PRODUCT;
DROP TABLE ORDERS;
DROP TABLE MEMBER;

CREATE TABLE MEMBER (
    MID VARCHAR2(50) PRIMARY KEY,
    MNAME VARCHAR2(20) NOT NULL,
    MEMAIL VARCHAR2(50) NOT NULL UNIQUE,
    MADDR VARCHAR2(255),
    MTEL VARCHAR2(20) NOT NULL
);

CREATE TABLE ORDERS (
    ONO VARCHAR2(9) PRIMARY KEY,
    MID VARCHAR2(50) REFERENCES MEMBER(MID) NOT NULL,
    ONAME VARCHAR2(20) NOT NULL,
    OADDR VARCHAR2(255) NOT NULL,
    OTEL VARCHAR2(20) NOT NULL,
    ODATE DATE DEFAULT SYSDATE 
);

CREATE TABLE PRODUCT(
    PCODE VARCHAR2(5) PRIMARY KEY,
    PNAME VARCHAR2(100) NOT NULL,
    PRICE NUMBER(6) CHECK (0 <= PRICE) NOT NULL,
    PSTOCK NUMBER(10) CHECK (0 <= PSTOCK) NOT NULL
);

CREATE TABLE ORDERDETAIL (
    ODNO NUMBER(9) PRIMARY KEY,
    ONO VARCHAR2(30) REFERENCES ORDERS(ONO) NOT NULL,
    PCODE VARCHAR2(20) REFERENCES PRODUCT(PCODE) NOT NULL,
    QTY NUMBER(10) CHECK (0 < QTY) NOT NULL,
    COST NUMBER(9)
);

CREATE TABLE CART (
    CNO NUMBER(9) PRIMARY KEY,
    PCODE VARCHAR2(20) REFERENCES PRODUCT(PCODE) NOT NULL,
    MID VARCHAR2(50) REFERENCES MEMBER(MID) NOT NULL,
    QTY NUMBER(10) CHECK (0 < QTY)NOT NULL,
    COST NUMBER(9) 
);

DROP SEQUENCE ONO_SQ;
DROP SEQUENCE CNO_SQ;
DROP SEQUENCE ODNO_SQ;

CREATE SEQUENCE ONO_SQ
    START WITH 001 
    MAXVALUE 999
    MINVALUE 001 
    NOCACHE;
    
CREATE SEQUENCE CNO_SQ  
    MAXVALUE 999  
    NOCACHE;
    
CREATE SEQUENCE ODNO_SQ
    MAXVALUE 999
    NOCACHE;
   
INSERT INTO MEMBER VALUES ('abc', '홍길동', 'abc@abc.com', '서울시 서대문구', '010-9999-9999');
INSERT INTO MEMBER VALUES ('def', '김김동', 'def@def.com', '경기도 수원시', '010-8888-8888');

INSERT INTO PRODUCT VALUES ('A1', '맥주', 3000, 30);
INSERT INTO PRODUCT VALUES ('A2', '마스크', 200, 100);
INSERT INTO PRODUCT VALUES ('B1', '땅콩', 3000, 20);
INSERT INTO PRODUCT VALUES ('B2', '오징어', 5000, 10);
INSERT INTO PRODUCT VALUES ('C1', '소독약', 7000, 10);
SELECT * FROM PRODUCT;

INSERT INTO CART VALUES (CNO_SQ.NEXTVAL, 'A1', 'abc', 3, (SELECT PRICE FROM PRODUCT WHERE PCODE = 'A1')*3);
INSERT INTO CART VALUES (CNO_SQ.NEXTVAL, 'B1', 'abc', 1, (SELECT PRICE FROM PRODUCT WHERE PCODE = 'B1')*1);
SELECT * FROM CART;

INSERT INTO ORDERS (ONO, MID, ONAME, OADDR, OTEL) VALUES (TO_CHAR(SYSDATE, 'RRMMDD')||LPAD(ONO_SQ.NEXTVAL, 3, '0'), 'abc', '홍길동', '서울시 서대문구 대현동', '010-9999-9999');
SELECT * FROM ORDERS;

  -- 서브쿼리 이용하여 장바구니의 모든 상품을 주문할 경우
INSERT INTO ORDERDETAIL (ODNO, ONO, PCODE, QTY, COST) SELECT ODNO_SQ.NEXTVAL, TO_CHAR(SYSDATE, 'RRMMDD')||LPAD(ONO_SQ.CURRVAL, 3, '0') ONO, PCODE, QTY, COST 
    FROM CART  WHERE MID = 'abc';
    
  -- 서브쿼리를 이용하지 않고 일부 상품만 구매할 경우 따로 따로 입력   
  -- A1, 맥주, 3000, 3개
INSERT INTO ORDERDETAIL (ODNO, ONO, PCODE, QTY, COST)
    VALUES (ODNO_SQ.NEXTVAL,
        TO_CHAR(SYSDATE, 'RRMMDD')||TRIM(TO_CHAR(ONO_SQ.CURRVAL, '000')),'A1', 3, (SELECT PRICE FROM PRODUCT WHERE pCODE='A1')*3);    
  -- B1, 땅콩, 3000, 1개
INSERT INTO ORDERDETAIL (ODNO, ONO, PCODE, QTY, COST)
    VALUES (ODNO_SQ.NEXTVAL,
        TO_CHAR(SYSDATE, 'RRMMDD')||TRIM(TO_CHAR(ONO_SQ.CURRVAL, '000')),'B1', 1, (SELECT PRICE FROM PRODUCT WHERE pCODE='B1')*1);
        
SELECT * FROM ORDERDETAIL;

UPDATE PRODUCT SET PSTOCK = PSTOCK - (SELECT QTY FROM ORDERDETAIL WHERE PCODE = 'A1') WHERE PCODE = 'A1';
UPDATE PRODUCT SET PSTOCK = PSTOCK - (SELECT QTY FROM ORDERDETAIL WHERE PCODE = 'B1') WHERE PCODE = 'B1';

SELECT * FROM PRODUCT;

DELETE FROM CART WHERE MID = 'abc'; --  장바구니 비우기

-- 주문서에 필요한 데이터 출력
--현재 주문번호만 SELECT절에 현재 시퀀스값을 이용하여 가져올 수 있으나 시퀀스.CURRVAL은 WHERE절에서 사용할 수 없음
SELECT * FROM ORDERS WHERE ONO=230102001;
SELECT O.PCODE, PNAME, PRICE, QTY, COST FROM ORDERDETAIL O, PRODUCT P WHERE O.PCODE=P.PCODE AND ONO = 230102001;
