SELECT ENAME, SAL FROM EMP WHERE SAL >= 1500 AND DEPTNO IN (10,30);
SELECT ENAME, SAL FROM EMP WHERE SAL >= 1500 AND DEPTNO IN (10, 30);
SELECT EMPNO, ENAME, HIREDATE, JOB, SAL
	FROM EMP
	WHERE TO_CHAR(HIREDATE,'RR')='81' AND JOB !='SALESMAN';
    
    SELECT EMPNO, ENAME, HIREDATE, JOB, SAL FROM EMP WHERE HIREDATE LIKE '81/__/__' AND JOB != 'SALESMAN';
    SELECT EMPNO, ENAME FROM EMP WHERE ENAME LIKE '__N%';
    
    SELECT EMPNO, ENAME FROM EMP WHERE ENAME LIKE '%A%';