DROP TABLE MEMBER;
DROP TABLE MEMBER_LEVEL;

CREATE TABLE MEMBER_LEVEL(
    LEVELNO NUMBER(1) PRIMARY KEY,
    LEVELNAME VARCHAR2(20) NOT NULL
);
CREATE TABLE MEMBER (
    MNO NUMBER(1) PRIMARY KEY,
    MNAME VARCHAR2(30) NOT NULL,
    MPW VARCHAR2(50) CHECK (LENGTH(MPW) BETWEEN 1 AND 8),
    MEMAIL VARCHAR2(50) UNIQUE,
    MPOINT NUMBER(10) CHECK (0 <= MPOINT),
    MRDATE DATE DEFAULT SYSDATE,
    LEVELNO NUMBER(1) REFERENCES MEMBER_LEVEL(LEVELNO)
);

DROP SEQUENCE MEMBER_MNO_SQ;
CREATE SEQUENCE MEMBER_MNO_SQ
    MAXVALUE 9999
    NOCACHE
    NOCYCLE
;

INSERT INTO MEMBER_LEVEL VALUES (-1, 'BLACK');
INSERT INTO MEMBER_LEVEL VALUES (0, 'ÀÏ¹Ý');
INSERT INTO MEMBER_LEVEL VALUES (1, '½Ç¹ö');
INSERT INTO MEMBER_LEVEL VALUES (2, '°ñµå');
SELECT * FROM MEMBER_LEVEL;

INSERT INTO MEMBER VALUES (MEMBER_MNO_SQ.NEXTVAL, 'È«±æµ¿', 'aa', 'hong@hong.com', 0, '22/03/10', 0);
INSERT INTO MEMBER VALUES (MEMBER_MNO_SQ.NEXTVAL, '½Å±æµ¿', 'bb', 'sin@sin.com', 1000, '22/04/10', 1);
SELECT * FROM MEMBER;

SELECT MNO, MNAME, TO_CHAR(MRDATE, 'RR-MM-DD') mRDATE, MEMAIL mMAEL, MPOINT POINT, LEVELNAME||'°í°´' LEVELNAME
    FROM MEMBER_LEVEL L, MEMBER M
    WHERE L.LEVELNO = M.LEVELNO;