DROP TABLE NOTICEBOARD;
DROP TABLE ADMIN;
DROP TABLE ONEREVIEWBOARD;
DROP TABLE RESTAURANT;
DROP TABLE CCODE;
DROP TABLE FREEBOARD;
DROP TABLE MEMBER;

DROP SEQUENCE NOTICE_SEQ;
DROP SEQUENCE RES_SEQ;
DROP SEQUENCE ONE_SEQ;
DROP SEQUENCE FREE_SEQ;
DROP SEQUENCE CCODE_SEQ;

CREATE TABLE MEMBER(
    MID VARCHAR2(50) PRIMARY KEY,
    MPW VARCHAR2(50) NOT NULL,
    MNAME VARCHAR2(50) NOT NULL,
    MEMAIL VARCHAR2(50),
    MTEL VARCHAR2(50),
    MGENDER VARCHAR2(10),
    MBIRTH DATE,
    MRDATE DATE DEFAULT SYSDATE,
    MWITHD NUMBER(1) DEFAULT 1
);

CREATE TABLE ADMIN(
    AID VARCHAR2(50) PRIMARY KEY,
    APW VARCHAR2(50) NOT NULL,
    ANAME VARCHAR2(50) NOT NULL
);

CREATE TABLE NOTICEBOARD(
    NNO NUMBER(6) PRIMARY KEY,
    AID VARCHAR2(50) REFERENCES ADMIN(AID) NOT NULL,
    NTITLE VARCHAR2(100) NOT NULL,
    NCONTENT VARCHAR2(4000) NOT NULL,
    NRDATE DATE DEFAULT SYSDATE,
    NHIT NUMBER(6) DEFAULT 0
);
CREATE TABLE CCODE (
    CNO NUMBER(2) PRIMARY KEY,
    CNAME VARCHAR2(50) NOT NULL
); 

CREATE TABLE RESTAURANT (
    RNO NUMBER(6) PRIMARY KEY,
    MID VARCHAR2(50) REFERENCES MEMBER(MID) NOT NULL,
    CNO NUMBER(2) REFERENCES CCODE(CNO) NOT NULL,
    RPLACE VARCHAR2(30) NOT NULL,
    RTITLE VARCHAR2(100) NOT NULL,
    RCONTENT VARCHAR2(4000) NOT NULL,
    RIMAGE1 VARCHAR2(50) NOT NULL,-- 대표 이미지
    RIMAGE2 VARCHAR2(50),
    RIMAGE3 VARCHAR2(50),
    RTEL VARCHAR2(50),
    RHIT NUMBER(6) DEFAULT 0 NOT NULL,
    RRDATE DATE DEFAULT SYSDATE,
    RSCORE NUMBER(1,1) DEFAULT 0 NOT NULL,
    SCOREHIT NUMBER(6) DEFAULT 0 NOT NULL -- 평점 등록 시 1중가(10 이상이고 평점이 4.5이상일 경우에만 추천페이지 출력)
);

CREATE TABLE ONEREVIEWBOARD (
    ONO NUMBER(6) PRIMARY KEY,
    RNO NUMBER(6) REFERENCES RESTAURANT(RNO) NOT NULL,
    OCONTENT VARCHAR2(2000) NOT NULL,
    OHAERT NUMBER(6) DEFAULT 0
);

CREATE TABLE FREEBOARD (
    FNO NUMBER(6) PRIMARY KEY,
    MID VARCHAR2(50) REFERENCES MEMBER(MID) NOT NULL,
    FTITLE VARCHAR2(100) NOT NULL,
    FCONTENT VARCHAR2(4000),
    FIMAGE1 VARCHAR2(50),
    FIMAGE2 VARCHAR2(50),
    FRDATE DATE DEFAULT SYSDATE,
    FGROUP NUMBER(6) NOT NULL,
    FSTEP NUMBER(6) NOT NULL,
    FINDENT NUMBER(6) NOT NULL
);

CREATE SEQUENCE NOTICE_SEQ MAXVALUE 999999 NOCACHE NOCYCLE;
CREATE SEQUENCE RES_SEQ MAXVALUE 999999 NOCACHE NOCYCLE;
CREATE SEQUENCE ONE_SEQ MAXVALUE 999999 NOCACHE NOCYCLE;
CREATE SEQUENCE FREE_SEQ MAXVALUE 999999 NOCACHE NOCYCLE;
CREATE SEQUENCE CCODE_SEQ MAXVALUE 99 NOCACHE NOCYCLE;

SELECT * FROM MEMBER;
SELECT * FROM NOTICEBOARD;
SELECT * FROM ADMIN;
SELECT * FROM CCODE;
SELECT * FROM RESTAURANT;
SELECT * FROM ONEREVIEWBOARD;
SELECT * FROM FREEBOARD;

COMMIT;