---- MEMBER
INSERT INTO MEMBER (MID, MPW, MNAME, MEMAIL, MGENDER, MBIRTH)
    VALUES ('AAA', '1', '홍', 'H@H.COM', '남', '1995-12-12');
INSERT INTO MEMBER (MID, MPW, MNAME, MEMAIL, MGENDER, MBIRTH)
    VALUES ('BBB', '1', '김', 'K@K.COM', '여', '1997-09-22');
INSERT INTO MEMBER (MID, MPW, MNAME, MEMAIL, MGENDER, MBIRTH)
    VALUES ('CCC', '1', '최', 'C@C.COM', '남', '1991-04-23');
 
---- ADMIN
INSERT INTO ADMIN (AID, APW, ANAME)
    VALUES ('ADMIN', '1', '관리자');
    
---- NOTICEBOARD
INSERT INTO NOTICEBOARD (NNO, AID, NTITLE, NCONTENT)
    VALUES (NOTICE_SEQ.NEXTVAL, 'ADMIN', '공지1', '본문');
INSERT INTO NOTICEBOARD (NNO, AID, NTITLE, NCONTENT)
    VALUES (NOTICE_SEQ.NEXTVAL, 'ADMIN', '공지2', '본문');
    
---- CCODE
INSERT INTO CCODE (CNO, CNAME)
    VALUES (CCODE_SEQ.NEXTVAL, '한식');
INSERT INTO CCODE (CNO, CNAME)
    VALUES (CCODE_SEQ.NEXTVAL, '일식');
INSERT INTO CCODE (CNO, CNAME)
    VALUES (CCODE_SEQ.NEXTVAL, '중식');

---- RESTAURNT
INSERT INTO RESTAURANT (RNO, MID, CNO, RPLACE, RTITLE, RCONTENT, RIMAGE1, RTEL)
    VALUES (RES_SEQ.NEXTVAL, 'AAA', 1, '종로', '종로부대찌개', '맛있음', 'IMAGE1', '02-111-1111');
INSERT INTO RESTAURANT (RNO, MID, CNO, RPLACE, RTITLE, RCONTENT, RIMAGE1, RTEL)
    VALUES (RES_SEQ.NEXTVAL, 'BBB', 2, '신촌', '신촌돈까스', '추천함', 'IMAGE2', '02-222-2222');
INSERT INTO RESTAURANT (RNO, MID, CNO, RPLACE, RTITLE, RCONTENT, RIMAGE1, RTEL)
    VALUES (RES_SEQ.NEXTVAL, 'BBB', 3, '강남', '강남마라탕', '굳', 'IMAGE2', '02-333-3333');

---- ONEREVIEWBOARD
INSERT INTO ONEREVIEWBOARD (ONO, RNO, OCONTENT)
    VALUES (ONE_SEQ.NEXTVAL, 1, '정말 맛있네요');
INSERT INTO ONEREVIEWBOARD (ONO, RNO, OCONTENT)
    VALUES (ONE_SEQ.NEXTVAL, 2, '별로에요');
INSERT INTO ONEREVIEWBOARD (ONO, RNO, OCONTENT)
    VALUES (ONE_SEQ.NEXTVAL, 3, '위생적이에요');
    
---- FREEBOARD
INSERT INTO FREEBOARD (FNO, MID, FTITLE, FCONTENT, FIMAGE1, FGROUP, FSTEP, FINDENT)
    VALUES (FREE_SEQ.NEXTVAL, 'AAA', '서울 맛집 추천해주세요', '신촌쪽 맛집 추천 부탁', NULL, FREE_SEQ.CURRVAL, 0, 0);
INSERT INTO FREEBOARD (FNO, MID, FTITLE, FCONTENT, FIMAGE1, FGROUP, FSTEP, FINDENT)
    VALUES (FREE_SEQ.NEXTVAL, 'BBB', '인천에 갈만한 곳 있나요?', '추천해주세요', NULL, FREE_SEQ.CURRVAL, 0, 0);
INSERT INTO FREEBOARD (FNO, MID, FTITLE, FCONTENT, FIMAGE1, FGROUP, FSTEP, FINDENT)
    VALUES (FREE_SEQ.NEXTVAL, 'CCC', '인천 여행지 추천합니다', '영종도 추천해요', 'IMAGE3', 2, 1, 1);
INSERT INTO FREEBOARD (FNO, MID, FTITLE, FCONTENT, FIMAGE1, FGROUP, FSTEP, FINDENT)
    VALUES (FREE_SEQ.NEXTVAL, 'BBB', '추천 감사합니다', '꼭 가볼게요', NULL, 2, 2, 2);
INSERT INTO FREEBOARD (FNO, MID, FTITLE, FCONTENT, FIMAGE1, FGROUP, FSTEP, FINDENT)
    VALUES (FREE_SEQ.NEXTVAL, 'BBB', '인천 다녀왔습니다', '좋네요', NULL, FREE_SEQ.CURRVAL, 0, 0);

COMMIT;