SELECT * FROM CUSLEVEL;
SELECT * FROM CUSTOMER;

-- 1 회원가입
INSERT INTO CUSTOMER (ID, TEL, CNAME) VALUES (CUSTOMER_ID_SQ.NEXTVAL, '010-8888-8889', '신길동'); 

-- 2 전화번호 4자리 검색

SELECT ID, TEL, CNAME, POINT, CUM_AMT, LEVELNAME, HIAMT-CUM_AMT "필요 누적금액"
    FROM CUSLEVEL, CUSTOMER WHERE CUM_AMT BETWEEN LOAMT AND HIAMT AND SUBSTR(TEL, -4,4) = SUBSTR('010-9234-9999', -4, 4);
    
-- 3 물품구입


-- 4 고객 등급별 출력



    





