-- 시퀀스와 테이블 drop & create 
DROP TABLE FRIEND;
DROP SEQUENCE FRIEND_NO_SEQ;
CREATE SEQUENCE FRIEND_NO_SEQ
    MAXVALUE 9999
    NOCACHE
    NOCYCLE;
CREATE TABLE FRIEND(
    NO NUMBER(4) PRIMARY KEY,
    NAME VARCHAR2(30) NOT NULL,
    TEL VARCHAR2(20)
);
SELECT * FROM FRIEND; 
-- 1 친구 추가 public int inputFriend(FriendDto dto)

INSERT INTO FRIEND (NO, NAME, TEL)
    VALUES (FRIEND_NO_SEQ.NEXTVAL, '홍길동', '010-9999-9999');

-- 2. 친구 목록 출력

SELECT * FROM FRIEND;

-- 3. 친구 검색

SELECT * FROM FRIEND WHERE NAME LIKE '%'||'홍'||'%' AND TEL LIKE '%'||'9999'||'%';

COMMIT;